apiVersion: v1
kind: Service
metadata:
  name: ngxapi
  labels:
    app: ngxapi
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: http
  selector:
    app: ngxapi
