# Default values for anginx.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: nginx
  tag: alpine
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

securityContext: {}
## We usually recommend to specify securityContext for containers
## This increases chances charts run on restricted environments such as OpenShift.
## If you do want to specify securityContext, uncomment the following
## lines, adjust them as necessary, and remove the curly braces after 'securityContext:'.
#  fsGroup: 65534
#  runAsUser: 65534

service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  port: 8080
  nodePort: ""

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: anginx.local
      paths: [/]

  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - anginx.local

## Create NetworkPolicy resources.
networkPolicy:
  enabled: false
## If you do want to specify egress, uncomment the following
#  egress:
#    - to:
#        - ipBlock: # Allow nodeapp to talk to external servers
#            cidr: 0.0.0.0/0
#    - ports: # Allow nodeapp to talk with the api server
#        - port: 6443
#          protocol: TCP
#        - port: 6443
#          protocol: UDP

resources: {}
#  limits:
#    cpu: 100m
#    memory: 128Mi
#  requests:
#    cpu: 100m
#    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
