apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "anginx.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "anginx.name" . }}
    helm.sh/chart: {{ include "anginx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
data:
{{ (tpl (.Files.Glob "files/*").AsConfig .) | indent 2 }}
