apiVersion: v1
kind: Template
metadata:
  name: ${APPNAME}
  annotations:
  tags: "mongodb,template"
  description: MongoDB template

objects:
- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    ports:
    - name: ${APPNAME}-27017-tcp
      port: 27017
      protocol: TCP
      targetPort: 27017
    selector:
      app: ${APPNAME}

- kind: PersistentVolumeClaim
  apiVersion: v1
  metadata:
    name: ${APPNAME}-data
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi

- kind: Secret
  apiVersion: v1
  metadata:
    labels:
      app: ${APPNAME}
    name: ${APPNAME}-secrets
  stringData:
    mangodb_password: cockpit123
    mangodb_admin_password: cockpit321

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    replicas: 1
    strategy:
      type: Rolling
    triggers:
    - type: ConfigChange
    selector:
      app: ${APPNAME}
    template:
      metadata:
        name: ${APPNAME}
        labels:
          app: ${APPNAME}
          deploymentConfig: ${APPNAME}
      spec:
        volumes:
        - name: ${APPNAME}-volume
          persistentVolumeClaim:
            claimName: ${APPNAME}-data
        containers:
        - name: ${APPNAME}
          image: ${DOCKERIMAGE}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 4G
            requests:
              memory: 2G
          ports:
          - containerPort: 27017
            protocol: TCP
          env:
          - name: MONGODB_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APPNAME}-secrets
                key: mangodb_admin_password
          - name: MONGODB_DATABASE
            value: cockpit
          - name: MONGODB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: ${APPNAME}-secrets
                key: mangodb_password
          - name: MONGODB_USER
            value: mdbuser
          volumeMounts:
            name: ${APPNAME}-volume
          - mountPath: /var/lib/mongodb/data

parameters:
- name: APPNAME
  value: mongodb
- name: DOCKERIMAGE
  value: registry.access.redhat.com/rhscl/mongodb-36-rhel7
