language: node_js
node_js:
- "stable"
cache:
  directories:
  - node_modules
script:
#- npm test
- echo "npm test temporarily disabled"
before_deploy:
- npm run build:mock
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github_token: $github_token
  target-branch: gh-pages
  local_dir: dist/apps/webapp
  on:
    branch: master
#    tags: true
