version: '3'
services:
  keycloak:
    image: xmlking/keycloak-openshift-stateless
    container_name: keycloak
    volumes:
    - $PWD/.docker/keycloak/realm-config:/opt/jboss/keycloak/realm-config
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin123
      DB_VENDOR: H2
      KEYCLOAK_USER_CACHE_ENABLED: "false"
      KEYCLOAK_REALM_CACHE_ENABLED: "false"
    ports:
    - 9080:9080
    - 9444:9443
    - 10990:10990
  mongodb:
    image: centos/mongodb-36-centos7
    container_name: mongodb
    ports:
    - 27017:27017
    environment:
    - MONGODB_ADMIN_PASSWORD=cockpit321
    - MONGODB_DATABASE=cockpit
    - MONGODB_USER=mdbuser
    - MONGODB_PASSWORD=cockpit123
    volumes:
    - /tmp/mongodb-data:/var/lib/mongodb/data
  api:
    build:
      context: .
      dockerfile: .docker/api/dev.dockerfile
    image: 'ngx-starter-kit-api:latest'
    container_name: api
    env_file:
      - development.env
    ports:
    - 3000:3000
    depends_on:
    - mongodb
  web:
    build:
      context: .
      dockerfile: .docker/webapp/prod.dockerfile
    image: ngx-starter-kit:latest
    container_name: web
    command: nginx -g 'daemon off;'
    volumes:
    - .docker/webapp/nginx.dev.conf:/etc/nginx/conf.d/nginx.conf:ro
    ports:
    - 4200:8080
    depends_on:
    - keycloak
    - api
volumes:
  uploads:
    driver: local
