version: '3'

services:

  postgres:
    image: postgres:10.2
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: admin

  keycloak:
    image: jboss/keycloak:3.4.3.Final
    container_name: keycloak
    environment:
      POSTGRES_PORT_5432_TCP_ADDR: postgres
      POSTGRES_DATABASE: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: admin
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - keycloak_themes:/opt/jboss/keycloak/themes
      - keycloak_deployments:/opt/jboss/keycloak/standalone/deployments
      - keycloak_data:/opt/jboss/keycloak/standalone/data
    ports:
      - 8080:8080
    depends_on:
      - postgres

  web:
    build:
      context: .
      dockerfile: .docker/prod.dockerfile
    image: is360-nx:latest
    container_name: web
    command: dockerize -template /etc/nginx/conf.d/nginx.conf.tmpl:/etc/nginx/conf.d/default.conf nginx -g 'daemon off;'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
#      - AUTH_BASE_URL=http://keycloak:8080
      - AUTH_BASE_URL=https://keycloak-is360-phase-2.ocp-ctc-core-nonprod.optum.com
    volumes:
      - .docker/nginx.conf.tmpl:/etc/nginx/conf.d/nginx.conf.tmpl:ro
    ports:
      - '80:8080'
    depends_on:
      - keycloak

volumes:
  uploads:
  postgres_data:
  keycloak_data:
  keycloak_themes:
  keycloak_deployments:
    driver: local
