version: '3'

services:
  keycloak:
    image: jboss/keycloak-openshift:4.0.0.Final
    container_name: keycloak
    command: ["start-keycloak.sh", "-b", "0.0.0.0", "-Dkeycloak.migration.action=import", "-Dkeycloak.migration.provider=dir", "-Dkeycloak.migration.dir=/opt/jboss/keycloak/realm-config", "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING", "-Djboss.socket.binding.port-offset=1000"]
    volumes:
    - $PWD/.docker/keycloak/realm-config:/opt/jboss/keycloak/realm-config
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_VENDOR: H2
    ports:
    - 9080:9080
    - 9444:9443
    - 10990:10990

  web:
    build:
      context: .
      dockerfile: .docker/prod.dockerfile
    image: ngx-starter-kit:latest
    container_name: web
    command: dockerize -template /etc/nginx/conf.d/nginx.conf.tmpl:/etc/nginx/conf.d/default.conf nginx -g 'daemon off;'
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=8080
      - AUTH_BASE_URL=http://keycloak:8080
    volumes:
      - .docker/nginx.conf.tmpl:/etc/nginx/conf.d/nginx.conf.tmpl:ro
    ports:
      - 80:8080
    depends_on:
      - keycloak

volumes:
  uploads:
    driver: local
