kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: keycloak
  namespace: ngx
  labels:
    app: keycloak
    chart: keycloak-4.11.1
    heritage: Tiller
    release: keycloak
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: keycloak-ngx.apps.us-east-2.online-starter.openshift.com
  to:
    kind: Service
    name: keycloak-http
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None

