kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: keycloak
  namespace: ngx
  selfLink: /apis/route.openshift.io/v1/namespaces/ngx/routes/keycloak
  uid: 20e5c137-7068-11e9-92bd-0a580a81004a
  resourceVersion: '6341960'
  creationTimestamp: '2019-05-07T01:33:34Z'
  labels:
    app: keycloak
    chart: keycloak-4.11.1
    heritage: Tiller
    release: keycloak
  annotations:
    openshift.io/host.generated: 'true'
spec:
  host: keycloak-ngx.apps.us-west-1.online-starter.openshift.com
  to:
    kind: Service
    name: keycloak-http
    weight: 100
  port:
    targetPort: http
  tls:
    termination: edge
  wildcardPolicy: None
status:
  ingress:
    - host: keycloak-ngx.apps.us-west-1.online-starter.openshift.com
      routerName: default
      conditions:
        - type: Admitted
          status: 'True'
          lastTransitionTime: '2019-05-07T01:33:34Z'
      wildcardPolicy: None
      routerCanonicalHostname: apps.us-west-1.online-starter.openshift.com
