apiVersion: v1
kind: Service
metadata:
  name: api
  namespace: ngx-starter-kit
  labels:
    app: api
spec:
  type: NodePort
  ports:
    - name: api-3000
      port: 3000
      nodePort: 31442
      protocol: TCP
  selector:
    app: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ngx-starter-kit
  labels:
    app: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      name: api
      labels:
        app: api
    spec:
      containers:
        - name: api
          image: xmlking/ngx-starter-kit-api:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: 4G
            requests:
              memory: 2G
          ports:
            - containerPort: 3000
              protocol: TCP
          env:
            - name: TYPEORM_HOST
              value: postgres
            - name: TYPEORM_PORT
              value: '5432'
            - name: TYPEORM_DATABASE
              value: cockpit
            - name: TYPEORM_USERNAME
              value: cockpit
            - name: TYPEORM_PASSWORD
              value: cockpit123
