apiVersion: v1
kind: Template
metadata:
  name: ${APPNAME}
  annotations:
    tags: "ngxweb, template"
    description: ngx-starter-kit webapp template

objects:
- kind: ConfigMap
  apiVersion: v1
  metadata:
    name: ${APPNAME}-config
  data:
    nginx.conf: |

- kind: Route
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    to:
      kind: Service
      name: ${APPNAME}
    tls:
      termination: edge
    port:
      targetPort: ${APPNAME}-8080

- kind: Service
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    ports:
    - name: ${APPNAME}-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      app: ${APPNAME}

- kind: DeploymentConfig
  apiVersion: v1
  metadata:
    name: ${APPNAME}
    labels:
      app: ${APPNAME}
  spec:
    replicas: 1
    strategy:
      type: Rolling
    triggers:
    - type: ConfigChange
    selector:
      app: ${APPNAME}
    template:
      metadata:
        name: ${APPNAME}
        labels:
          app: ${APPNAME}
          deploymentConfig: ${APPNAME}
      spec:
        volumes:
        - name: ${APPNAME}-volume
          configMap:
            defaultMode: 420
            name: ${APPNAME}-config
        containers:
        - name: ${APPNAME}
          image: ${DOCKERIMAGE}
          imagePullPolicy: Always
          resources:
            limits:
              memory: 2G
            requests:
              memory: 1G
          ports:
          - containerPort: 8080
            name: ${APPNAME}
          volumeMounts:
          - name: ${APPNAME}-volume
            mountPath: /etc/nginx/conf.d/

parameters:
- name: APPNAME
  value: webapp
- name: DOCKERIMAGE
  value: xmlking/ngxweb:latest
