test:
  enabled: false

resources:
  limits:
    cpu: 2
    memory: "2048Mi"
  requests:
    cpu: 1
    memory: "1024Mi"

image:
  repository: xmlking/ngxapp
  tag: 1.5.0-SNAPSHOT
  pullPolicy: IfNotPresent

securityContext:
  fsGroup: 65534
  runAsUser: 65534
