{{- if .Values.managedcertificate.enabled -}}
apiVersion: networking.gke.io/v1beta1
kind: ManagedCertificate
metadata:
  name: {{ include "nodeapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nodeapp.name" . }}
    helm.sh/chart: {{ include "nodeapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.managedcertificate.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  domains:
    -  {{ .Values.managedcertificate.host }}
{{- end }}
