{{- if .Values.envSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nodeapp.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "nodeapp.name" . }}
    helm.sh/chart: {{ include "nodeapp.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
data:
  {{- range .Values.envSecrets }}
  {{ .name }}: {{ .value | b64enc | quote }}
  {{- end }}
{{- end }}
