apiVersion: v1
kind: Secret
metadata:
  name: postgres-init-scripts
  labels:
    app: postgresql
  annotations:
    "helm.sh/resource-policy": keep
type: Opaque
stringData:
  keycloak-db-password: keycloak123
  keycloak-db-init.sql: |-
    CREATE ROLE keycloak WITH PASSWORD 'keycloak123' NOSUPERUSER LOGIN;
    CREATE DATABASE keycloak;
    GRANT ALL PRIVILEGES ON DATABASE keycloak TO keycloak;

