name: Test on Push for API
on:
  push:
    paths:
      - 'apps/api/*'
jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 13.x
        uses: actions/setup-node@v1
        with:
          node-version: 13.x
          # registry-url: <registry url>
        id: node
      - name: Setup Tools
        run: |
          # npm install -g lerna
          npm install -g @angular/cli
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Check out Code
        uses: actions/checkout@v2
      - name: Cache node modules
        id: yarn-cache
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install Dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Lint
        run: yarn ng lint api
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Unit Test
        run: yarn ng test api
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - name: Integration Test
      #   run: yarn ng e2e api
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
          -F unittests
          -n codecov-ngx-api
          -f ./coverage/apps/api/coverage-final.json
          -B "${GITHUB_REF//refs\/heads\//}"
          -T "${GITHUB_REF//refs\/tags\//}"
          -C "${GITHUB_SHA}"
          -Z || echo 'Codecov upload failed'
        env:
          CI: true
          CODECOV_ENV: github-action
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_PR: ${{ github.event.after }}
          CODECOV_SHA: ${{ github.sha }}
