on: push
name: Main
jobs:
  lint-test:
    name: WebApp Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Upload coverage to Codecov
        run: echo
          -F unittests
          -n codecov-ngx
          -f ./coverage/libs/ngx-utils/coverage-final.json
          -B "${GITHUB_REF//refs\/heads\//}"
          -T "${GITHUB_REF//refs\/tags\//}"
          -C "${GITHUB_SHA}"
          -Z || echo 'Codecov upload failed'
        env:
          CI: true
          CODECOV_ENV: github-action
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
          CODECOV_PR: ${{ github.event.number }}
