on: push
name: Main
jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # - name: Setup Angular CLI
      #   run: yarn global add @angular/cli
      #   env:
      #     NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Install Dependencies
        run: yarn install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Linting
        run: yarn ng lint ngx-utils
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Testing
        run: yarn ng test ngx-utils
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Upload coverage to Codecov
        run: bash <(curl -s https://codecov.io/bash)
          -F unittests
          -n codecov-ngx
          -f ./coverage/libs/ngx-utils/coverage-final.json
          -B ${{ github.GITHUB_REF }}
          -C ${{ github.event.after }}
          -P ${{ github.event.number }}
          -Z || echo 'Codecov upload failed'
        env:
          CI: true
          CODECOV_ENV: github-action
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
