name: Test on Push for WebApp
on: push
jobs:
  lint-test:
    name: Lint and Test
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          # registry-url: <registry url>
        id: node
      - name: Setup Tools
        run: |
          echo $NPM_TOKEN
          echo $NODE_AUTH_TOKEN
